version: '3.9'

services:
  bot:
    build: .
    command: "python3 -m bot"
    volumes:
      - .:/bot
    networks:
      - bot
    env_file:
      - .env
    restart: always

networks:
  bot:
    driver: bridge
